import {firebaseConfig} from "./firebase-config.js";
import{equipmentImageMarkup,bindEquipmentImageFallbacks}from"./equipment-images.js";
import{initializeApp}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import{getFirestore,doc,onSnapshot}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
const app=initializeApp(firebaseConfig),db=getFirestore(app),$=id=>document.getElementById(id);let current,unsub;
$("buscarCita").onclick=()=>watch($("folioCita").value.trim().toUpperCase());
function watch(f){if(!f)return;if(unsub)unsub();$("folioCita").value=f;unsub=onSnapshot(doc(db,"citas_publicas",f),s=>{if(!s.exists()){$("msgCita").textContent="Folio de cita no encontrado.";$("resultadoCita").classList.add("hidden");return}current={id:s.id,...s.data()};render()},()=>$("msgCita").textContent="No fue posible consultar la cita.")}
function render(){$("msgCita").textContent="";$("resultadoCita").classList.remove("hidden");$("cFolio").textContent=current.id;$("cEstado").textContent=current.estado;$("cFechaHora").textContent=`${formatearFecha(current.fecha)} · ${formatearHora(current.hora)}`;$("cCliente").textContent=current.cliente;$("cEquipo").textContent=current.equipo;$("cModelo").textContent=current.modelo||"No especificado";$("cFalla").textContent=current.falla||"No especificada";$("appointmentEquipmentImage").innerHTML=equipmentImageMarkup(current.equipo,current.modelo);bindEquipmentImageFallbacks($("appointmentEquipmentImage"));$("cHistorial").innerHTML=(current.historial||[]).slice().reverse().map(h=>`<div class="history-entry"><small>${new Date(h.fecha).toLocaleString("es-MX")}</small><b>${esc(h.tipo)}</b><span>${esc(h.detalle||"")}</span></div>`).join("")||"<p>Sin movimientos.</p>"}
$("pedirReagendar").onclick=()=>{if(!current)return;const m=`Hola, soy ${current.cliente}.\n\nFolio: ${current.id}\n\nMe gustaría solicitar reagendar mi cita.\n\nGracias.`;window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(m)}`,"_blank")};
$("solicitarLlamada").onclick=()=>{if(!current)return;const m=`Hola, soy ${current.cliente}.\n\nFolio: ${current.id}\n\nMe gustaría comunicarme con el equipo de XE Servicio Electrónico. Cuando tengan oportunidad, ¿podrían llamarme por WhatsApp?\n\nGracias.`;window.open(`https://api.whatsapp.com/send?text=${encodeURIComponent(m)}`,"_blank")};
$("descargarPdf").onclick=()=>generarPDF(current);
function generarPDF(x){
 if(!x||!window.jspdf)return alert("No se pudo cargar el generador PDF.");
 const{jsPDF}=window.jspdf,p=new jsPDF(),azul=[14,67,116],plata=[137,151,166];
 p.setFillColor(247,249,251);p.rect(0,0,210,297,"F");p.setDrawColor(...azul);p.setLineWidth(1.2);p.roundedRect(8,8,194,281,3,3,"S");p.setDrawColor(...plata);p.setLineWidth(.35);p.roundedRect(11,11,188,275,2,2,"S");
 p.setFillColor(...azul);p.roundedRect(13,13,184,39,3,3,"F");p.setFillColor(232,237,242);p.roundedRect(19,19,27,27,4,4,"F");p.setTextColor(...azul);p.setFont("helvetica","bold");p.setFontSize(19);p.text("XE",32.5,37,{align:"center"});
 p.setTextColor(255,255,255);p.setFontSize(17);p.text("CONFIRMACIÓN DE CITA",55,30);p.setFont("helvetica","normal");p.setFontSize(8);p.text("XE SERVICIO ELECTRÓNICO · ATENCIÓN PROGRAMADA",55,40);
 p.setFillColor(229,236,243);p.setDrawColor(...plata);p.roundedRect(18,59,174,27,3,3,"FD");p.setTextColor(...azul);p.setFont("helvetica","bold");p.setFontSize(8);p.text("FOLIO DE CITA",26,69);p.setFontSize(17);p.text(x.id,184,77,{align:"right"});
 const campo=(et,val,xp,yp,w)=>{p.setFillColor(255,255,255);p.setDrawColor(220,225,230);p.roundedRect(xp,yp,w,22,2,2,"FD");p.setTextColor(...azul);p.setFont("helvetica","bold");p.setFontSize(7);p.text(et.toUpperCase(),xp+5,yp+7);p.setTextColor(45,48,52);p.setFont("helvetica","normal");p.setFontSize(9);p.text(p.splitTextToSize(String(val||"No especificado"),w-10).slice(0,2),xp+5,yp+14)};
 campo("Cliente",x.cliente,18,93,85);campo("WhatsApp",x.telefono||"No especificado",107,93,85);campo("Equipo",x.equipo,18,119,85);campo("Modelo",x.modelo||"No especificado",107,119,85);
 campo("Fecha",formatearFecha(x.fecha),18,145,85);campo("Hora",formatearHora(x.hora),107,145,85);
 p.setFillColor(255,255,255);p.setDrawColor(220,225,230);p.roundedRect(18,171,174,37,2,2,"FD");p.setTextColor(...azul);p.setFont("helvetica","bold");p.setFontSize(7);p.text("FALLA REPORTADA",23,179);p.setTextColor(45,48,52);p.setFont("helvetica","normal");p.setFontSize(9);p.text(p.splitTextToSize(String(x.falla||"No especificada"),164).slice(0,4),23,187);
 p.setFillColor(...azul);p.roundedRect(18,216,174,24,3,3,"F");p.setTextColor(255,255,255);p.setFont("helvetica","bold");p.setFontSize(8);p.text("ESTADO DE LA CITA",26,226);p.setFontSize(13);p.text(String(x.estado||"Confirmada").toUpperCase(),184,231,{align:"right"});
 p.setDrawColor(...plata);p.line(18,270,192,270);p.setTextColor(38,42,46);p.setFont("helvetica","bold");p.setFontSize(9);p.text("XE SERVICIO ELECTRÓNICO",105,278,{align:"center"});p.setFont("helvetica","normal");p.setFontSize(8);p.text("EXPERTOS EN TECNOLOGÍA",105,284,{align:"center"});p.save(`Cita-${x.id}.pdf`)
}
function formatearFecha(v){return v?new Date(v+"T12:00:00").toLocaleDateString("es-MX",{weekday:"long",day:"numeric",month:"long",year:"numeric"}):"Sin fecha"}function formatearHora(v){if(!v)return"Sin hora";const[h,m]=v.split(":");return new Date(2000,0,1,+h,+m).toLocaleTimeString("es-MX",{hour:"numeric",minute:"2-digit"})}function esc(s){return String(s||"").replace(/[&<>\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}
const f=new URLSearchParams(location.search).get("folio");if(f)watch(f.trim().toUpperCase());
